### ISSUE TITLE
unable to launch, java error

### ISSUE THREAD

**Issue by Merlin-09** [pnmougel/meow#4]
Hello,
this is a great app, but I don't know why, after a reinstallation of gnome-ubuntu yakkety, I cannot launch it anymore. Here is the terminal output.

`merlin@Merlin-portable:~$ meow
java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
	at java.base/java.lang.Class.getField(Class.java:1906)
	at com.alee.utils.ReflectUtils.getStaticFieldValue(ReflectUtils.java:630)
	at com.alee.utils.ProprietaryUtils.setupUIDefaults(ProprietaryUtils.java:92)
	at com.alee.laf.WebLookAndFeel.initComponentDefaults(WebLookAndFeel.java:536)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:932)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:918)
	at org.medit.gui.Main$.initGUI(Main.scala:41)
	at org.medit.gui.Runner$.main(Runner.scala:15)
	at org.medit.gui.Runner.main(Runner.scala)
java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:807)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at com.alee.utils.XmlUtils.initializeXStream(XmlUtils.java:90)
	at com.alee.utils.XmlUtils.getXStream(XmlUtils.java:77)
	at com.alee.utils.XmlUtils.processAnnotations(XmlUtils.java:141)
	at com.alee.laf.WebLookAndFeel$2.propertyChange(WebLookAndFeel.java:855)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:596)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:932)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:918)
	at org.medit.gui.Main$.initGUI(Main.scala:41)
	at org.medit.gui.Runner$.main(Runner.scala:15)
	at org.medit.gui.Runner.main(Runner.scala)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @64a8c844
	at java.base/jdk.internal.reflect.Reflection.throwInaccessibleObjectException(Reflection.java:427)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:201)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:171)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:165)
	at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	... 20 more
java.lang.NullPointerException
	at com.alee.utils.XmlUtils.processAnnotations(XmlUtils.java:141)
	at com.alee.laf.WebLookAndFeel$2.propertyChange(WebLookAndFeel.java:855)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:596)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:932)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:918)
	at org.medit.gui.Main$.initGUI(Main.scala:41)
	at org.medit.gui.Runner$.main(Runner.scala:15)
	at org.medit.gui.Runner.main(Runner.scala)
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:807)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at com.alee.utils.XmlUtils.initializeXStream(XmlUtils.java:90)
	at com.alee.utils.XmlUtils.getXStream(XmlUtils.java:77)
	at com.alee.utils.XmlUtils.processAnnotations(XmlUtils.java:141)
	at com.alee.managers.style.StyleManager.<clinit>(StyleManager.java:66)
	at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:106)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:683)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at com.alee.laf.panel.WebPanel.updateUI(WebPanel.java:913)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:95)
	at com.alee.laf.panel.WebPanel.<init>(WebPanel.java:164)
	at org.medit.gui.panels.LeftMenu$.<init>(LeftMenu.scala:13)
	at org.medit.gui.panels.LeftMenu$.<clinit>(LeftMenu.scala)
	at org.medit.gui.Main$.createAndShowGUI(Main.scala:73)
	at org.medit.gui.Main$$anon$2.run(Main.scala:59)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:759)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:712)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:79)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:729)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.ExceptionInInitializerError
	at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:106)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:683)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at com.alee.laf.panel.WebPanel.updateUI(WebPanel.java:913)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:95)
	at com.alee.laf.panel.WebPanel.<init>(WebPanel.java:164)
	at org.medit.gui.panels.LeftMenu$.<init>(LeftMenu.scala:13)
	at org.medit.gui.panels.LeftMenu$.<clinit>(LeftMenu.scala)
	at org.medit.gui.Main$.createAndShowGUI(Main.scala:73)
	at org.medit.gui.Main$$anon$2.run(Main.scala:59)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:759)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:712)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:79)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:729)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at com.alee.utils.XmlUtils.processAnnotations(XmlUtils.java:141)
	at com.alee.managers.style.StyleManager.<clinit>(StyleManager.java:66)
	... 25 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.alee.managers.style.StyleManager
	at com.alee.laf.panel.WebPanelUI.uninstallUI(WebPanelUI.java:132)
	at java.desktop/javax.swing.JComponent.uninstallUIAndProperties(JComponent.java:698)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:673)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at com.alee.laf.panel.WebPanel.updateUI(WebPanel.java:918)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:95)
	at com.alee.laf.panel.WebPanel.<init>(WebPanel.java:164)
	at org.medit.gui.panels.LeftMenu$.<init>(LeftMenu.scala:13)
	at org.medit.gui.panels.LeftMenu$.<clinit>(LeftMenu.scala)
	at org.medit.gui.Main$.createAndShowGUI(Main.scala:73)
	at org.medit.gui.Main$$anon$2.run(Main.scala:59)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:759)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:712)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:79)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:729)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`
could someone point me in a direction to solve this? thanks a lot for your work anyway :)

**Comment by gerardo-junior** [comment]
+1

**Comment by Benjamin-Saul-1989** [comment]
+1

**Comment by link0802** [comment]
I believe it happened due to changes made in JDK 9. Something like https://github.com/mgarin/weblaf/issues/452. Unfortunately, currently, I haven't access to my Linux laptop to test it and make pull request  :(

**Comment by mgarin** [comment]
Yes, I can confirm that this is a WebLaF issue which appeared due to major internal changes made to the text antialias rendering within JDK 9. It basically happened because L&F developers were forced to access proprietary Sun API if they wanted to provide any kind of text rendering configurations at all. 

Even though JDK 9 is not yet officially released (should be coming around July) and I do not generally recommend using it with WebLaF yet as there might be other various issues popping out - I will be pushing an update that will patch all currently known problems with it somewhere in the middle of the next week.

The only problem - those fixes will be going into WebLaF [styling](https://github.com/mgarin/weblaf/tree/styling) branch code and builds, but [meow](https://github.com/pnmougel/meow) project (according to [build file](https://github.com/pnmougel/meow/blob/master/project/Build.scala)) uses older v1.28 version which will certainly not work on JDK 9 and later ones. So it is up to @pnmougel whether he will be updating the project or not.

In the meantime you can switch back to JDK 8 or earlier versions to avoid this issue, unless it is critical for your project to run under current JDK 9 ea builds.
